### ISSUE TITLE
Request: Add Option to Display Block Height and Other Bitcoin Statistics

### ISSUE THREAD

**Issue by corbimos** [dr-mod/zero-btc-screen#11]
The ability to cycle through other Bitcoin metrics in addition to the price would be great. Ideally, a user could choose from a list of various stats and have it cycle through the selected data points. 

Metric examples would be like on [Clark Moody's Dashboard ](https://bitcoin.clarkmoody.com/dashboard/) or [Mempool.space](https://mempool.space/)

**Comment by dr-mod** [comment]
Hi @corbimos , at the moment there are no plans to extend the platform to support the metrics you mentioned.
