### ISSUE TITLE
Missing git dependency in guide

### ISSUE THREAD

**Issue by IzzoYourNizzo** [dr-mod/zero-btc-screen#14]
An amazing little project, thank you!

Just as a heads up, in your guide, for newbies out there you may want to include git as a dependency.

Simply:
`sudo apt install git`

**Comment by dr-mod** [comment]
Great that you like the project!
Initially, I intentionally omitted adding git as a dependency as it's not a dependency for the project per se. But if you believe that it will make the installation process for newbies easier, I'll definitely add it. Thanks for pointing this out! :)
