### ISSUE TITLE
Waveshare 2.13inch e-Paper HAT v2 screen update not working

### ISSUE THREAD

**Issue by WhoAmBy** [dr-mod/zero-btc-screen#15]
It looks like I've encountered some kind of glitch/bug that affects screen update. Prices are fetching, everything seems to be working fine in the logs but I'm only able to update the prices on the screen by resetting the running program - that's the only way to update the screen.
Doesn't matter if the interval is set for 1 minute, 3 or 15.
<img width="411" alt="Screenshot 2022-01-17 at 23 24 28" src="https://user-images.githubusercontent.com/35840549/149843296-ba67c601-9ee6-41d2-8c12-2f393aad4674.png">
 
Any ideas what could go wrong?

**Comment by dr-mod** [comment]
Hi @WhoAmBy, you could try configuring the "picture" screen to see if it updates as expected to eliminate any issues with that part. As for the screen not being updated, for a non-intrusive update the partial display update functionality is used, you could check if your display supports it and use full display update if it doesn't.

**Comment by WhoAmBy** [comment]
Alright, so I've checked if it updates correctly by changing the waveshare to picture screen, it's worth mentioning in docs that it saves in the /home/pi/output.png, looks like it updates correctly.
Had timer in my hand and the screen IS updating but every 15 minutes, prices are fetched every minute... 
How can i enable full display update?

**Comment by WhoAmBy** [comment]
Runned e-Paper Jetson-Nano python script `epd_2in13_V2_test.py` and it worked just fine

**Comment by ravnx** [comment]
Mine's been running untouched on a shelf, as of today just flashing the screen now. Running epd_2in13_V2_test.py also works fine for me. Looks like a bug somewhere in the update.

**Comment by dr-mod** [comment]
Feel free to change the image filename, it could be set in the config file, with the default filename described in the configuration section of readme. But based on your last message, it seems that you installed everything correctly. While you fetch data every minute, the default data-source aggregates prices every 15 minutes. Therefore, If you don't plan on using a different time range or API, I recommend using the default update time.

**Comment by dr-mod** [comment]
It seems that the issue is resolved for now, please let me know if there is something that doesn't seem to be working properly.
