### ISSUE TITLE
Display has gone blank and flashing today

### ISSUE THREAD

**Issue by romancerny** [dr-mod/zero-btc-screen#17]
pi@raspberrypi:~ $ python3 ~/zero-btc-screen/main.py
Traceback (most recent call last):
  File "/home/pi/zero-btc-screen/main.py", line 60, in <module>
    main()
  File "/home/pi/zero-btc-screen/main.py", line 46, in main
    data_sink.update_observers(prices)
  File "/home/pi/zero-btc-screen/presentation/observer.py", line 18, in update_observers
    observer.update(data)
  File "/home/pi/zero-btc-screen/presentation/screens/epd2in13v2.py", line 54, in update
    self.form_image(data, self.screen_draw)
  File "/home/pi/zero-btc-screen/presentation/screens/epd2in13v2.py", line 41, in form_image
    Plot.candle(prices, size=(SCREEN_WIDTH - 45, 93), position=(41, 0), draw=screen_draw)
  File "/home/pi/zero-btc-screen/data/plot.py", line 61, in candle
    for i in range(data_offset, len(data), windows_per_candle):
ValueError: range() arg 3 must not be zero

I have tried re-flashing the whole system and re-installing all dependencies, but the issue still persists.

Please advise.

**Comment by romancerny** [comment]
Prior to today, it worked all well without any issues on refresh rate 1 min, 5 min and 15 min

**Comment by ravnx** [comment]
Not sure what happened, must be a bug in the code with the dataset. I see the array for "data" is coming back 0 length. But its an array of arrays. (I'm not familiar with this code). Must be the dataset changed? 

I notice if i change to line instead of candle, its working for me.

**Comment by dr-mod** [comment]
There seems to be an issue with the data returned by the API, to be precise the last data frame is dated _GMT: Sunday, January 23, 2022 3:29:59 AM_. If this continues we just need to use another data source, I see that v3 works just fine, though has per-minute data.

**Comment by romancerny** [comment]
Thanks, guys for the quick response. Hopefully, the data provider will sort that out soon. 

It would be nice to have that caught and display a message on the display

**Comment by ravnx** [comment]
Yeah seeing my graph slowly disappear, definitely no data coming anymore.

**Comment by alex27riva** [comment]
Hi everyone, mine doesn't work anymore either.
I also had a [similar issue](https://github.com/dr-mod/zero-btc-screen/issues/13) few months ago.

**Comment by romancerny** [comment]
Yep, the Coindesk stopped returning data in their API call. Could we have an alternative data source? e.g. Coingecko?

https://api.coingecko.com/api/v3/coins/bitcoin/ohlc?vs_currency=usd&days=1

**Comment by dr-mod** [comment]
As the API is up and running again, I don't think there is a need of migrating to a new one. If, however, it becomes unstable, the one above could be a viable option.

**Comment by romancerny** [comment]
sounds good. Thanks
