### ISSUE TITLE
Request: support for Waveshare epd2in13v3

### ISSUE THREAD

**Issue by 0xhackworth** [dr-mod/zero-btc-screen#18]
I received my Waveshare HAT today it's EPD_2in13_V3 (not Bv3).  Any chance v3 can be supported?

**Comment by dr-mod** [comment]
Hi @0xhackworth, I've just pushed a new [branch](https://github.com/dr-mod/zero-btc-screen/tree/epd2in13v3_support) which includes support for the v3. But as I don't have this new display, I couldn't test it. 
Feel free to try it out and let me know if it works.

**Comment by 0xhackworth** [comment]
@dr-mod 

Wow, incredible -- thanks!!  Only thing is that about 60% of the screen is weirdly faded.  The driver tests don't have this issue, so I don't think it's a hardware issue.  Any thoughts?

[https://imgur.com/evtHFZP](url)
