### ISSUE TITLE
module 'presentation.screens.epd2in7' has no attribute 'Epd2in7'

### ISSUE THREAD

**Issue by ppauly** [dr-mod/zero-btc-screen#27]
Getting this traceback with a Waveshare 2.7 inch e-Paper hat:

python3 ~/zero-btc-screen/main.py
module 'presentation.screens.epd2in7' has no attribute 'Epd2in7'
Traceback (most recent call last):
  File "/home/pi/zero-btc-screen/config/builder.py", line 17, in bind
    screen_class = getattr(package, screen.lower().capitalize())
AttributeError: module 'presentation.screens.epd2in7' has no attribute 'Epd2in7'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/zero-btc-screen/main.py", line 60, in <module>
    main()
  File "/home/pi/zero-btc-screen/main.py", line 40, in main
    builder.bind(data_sink)
  File "/home/pi/zero-btc-screen/config/builder.py", line 27, in bind
    raise BtcConfigError(
config.builder.BtcConfigError: Cannot instantiate epd2in7

**Comment by ppauly** [comment]
Changing Epd2in7v1 to Epd2in7 and changing the config mode to line allows me to finally see a display.  Looks like someone was in the middle of changing the code.

**Comment by dr-mod** [comment]
Hi @ppauly, very good find, thanks for the feedback! Unfortunately, I don't have a 2.7 display and cannot check it. Feel free to to create a pull request with your changes. As for the upside-down issue, I'm not confident I'm following but if it has to do with the rotation you can change it here: 
https://github.com/dr-mod/zero-btc-screen/blob/c9a439ec61c4dcd3ad40878906563f365501e54e/presentation/screens/epd2in7.py#L52
