### ISSUE TITLE
Pico W

### ISSUE THREAD

**Issue by holmesha** [dr-mod/zero-btc-screen#28]
Do you think this could be replicated with a Pico W and the Pico Display?

**Comment by dr-mod** [comment]
Hi @holmesha, with adequate amount of change it could be adapted to the aforementioned platform. Would you like to try?

**Comment by pgghub** [comment]
Hi @dr-mod,

I have a Raspberry Pico W and a Waveshare 2.9 screen (RBW) (https://www.waveshare.com/pico-epaper-2.9-b.htm) 

I am wondering if I can get this to work with the Pico W (https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html) but I am not sure on the storage option. 

I started following the video on youtube and I don't have a storage option.
