### ISSUE TITLE
Name 'epd2in13_V2' is not defined

### ISSUE THREAD

**Issue by Jello-exe** [dr-mod/zero-btc-screen#29]
I am trying to run this on a Raspberry Pi 3 model B with Kali Linux installed. When I run the main python script I get these errors:

`Traceback (most recent call last):
File "/home/kali/zero-btc-screen/main.py", line 60, in <module>
main()
File "/home/kali/zero-btc-screen/main.py", line 40, in main
builder.bind(data_sink)
File "/home/kali/zero-btc-screen/config/builder.py", line 23, in bind
screen_class(observable=observable, **kwargs)
File "/home/kali/zero-btc-screen/presentation/screens/epd2in13v2.py", line 23, in __init__
self.epd = self._init_display()
File "/home/kali/zero-btc-screen/presentation/screens/epd2in13v2.py", line 30, in _init_display
epd = epd2in13_V2.EPD()
NameError: name 'epd2in13_V2' is not defined. Did you mean: 'Epd2in13v2'?`

 I have tried changing the name in the code and stuff like that but more errors kept coming up.
What can I do to fix this?

**Comment by dr-mod** [comment]
Hi @Jello-exe, based on the stack-trace it seems you haven't installed the e-paper drivers successfully.
Try going over the 3rd step of the installation process again, namely:
```
git clone https://github.com/waveshare/e-Paper.git ~/e-Paper
pip3 install ~/e-Paper/RaspberryPi_JetsonNano/python/
``` 
Looking forward to hear if this helps.

**Comment by Jello-exe** [comment]
Thank you for the reply!
This is the output of those 2 commands:
`Cloning into '/home/kali/e-Paper'...
remote: Enumerating objects: 7056, done.
remote: Counting objects: 100% (406/406), done.
remote: Compressing objects: 100% (144/144), done.
remote: Total 7056 (delta 254), reused 377 (delta 248), pack-reused 6650
Receiving objects: 100% (7056/7056), 40.39 MiB | 2.52 MiB/s, done.
Resolving deltas: 100% (4809/4809), done.
Updating files: 100% (2423/2423), done.
Defaulting to user installation because normal site-packages is not writeable
Processing ./e-Paper/RaspberryPi_JetsonNano/python
Preparing metadata (setup.py) ... done
Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from waveshare-epd==0.0.0) (9.2.0)
Requirement already satisfied: RPi.GPIO in /usr/local/lib/python3.10/dist-packages (from waveshare-epd==0.0.0)(0.7.1)
Requirement already satisfied: spidev in /usr/local/lib/python3.10/dist-packages (from waveshare-epd==0.0.0) (3.5)
Building wheels for collected packages: waveshare-epd
Building wheel for waveshare-epd (setup.py) ... done
Created wheel for waveshare-epd: filename=waveshare_epd-0.0.0-py3-none-any.whl size=115457 sha256=f12d92adf4952828b0f290176402f06c8b9d3dd0eb8219b82a784948b3b7a9e7
Stored in directory: /tmp/pip-ephem-wheel-cache-1ikebtcr/wheels/77/6e/4a/3529e563189e81cf9b666571c9ce05e32b21b691f215f36d6b
Successfully built waveshare-epd
Installing collected packages: waveshare-epd
Attempting uninstall: waveshare-epd
Found existing installation: waveshare-epd 0.0.0
Uninstalling waveshare-epd-0.0.0:
Successfully uninstalled waveshare-epd-0.0.0
Successfully installed waveshare-epd-0.0.0`

I don't see anything weird in there.

**Comment by Jello-exe** [comment]
Thank you for the reply!
This is the output of those 2 commands:
Cloning into '/home/kali/e-Paper'... remote: Enumerating objects: 7056, done. remote: Counting objects: 100% (406/406), done. remote: Compressing objects: 100% (144/144), done. remote: Total 7056 (delta 254), reused 377 (delta 248), pack-reused 6650 Receiving objects: 100% (7056/7056), 40.39 MiB | 2.52 MiB/s, done. Resolving deltas: 100% (4809/4809), done. Updating files: 100% (2423/2423), done. Defaulting to user installation because normal site-packages is not writeable Processing ./e-Paper/RaspberryPi_JetsonNano/python Preparing metadata (setup.py) ... done Requirement already satisfied: Pillow in /usr/lib/python3/dist-packages (from waveshare-epd==0.0.0) (9.2.0) Requirement already satisfied: RPi.GPIO in /usr/local/lib/python3.10/dist-packages (from waveshare-epd==0.0.0)(0.7.1) Requirement already satisfied: spidev in /usr/local/lib/python3.10/dist-packages (from waveshare-epd==0.0.0) (3.5) Building wheels for collected packages: waveshare-epd Building wheel for waveshare-epd (setup.py) ... done Created wheel for waveshare-epd: filename=waveshare_epd-0.0.0-py3-none-any.whl size=115457 sha256=f12d92adf4952828b0f290176402f06c8b9d3dd0eb8219b82a784948b3b7a9e7 Stored in directory: /tmp/pip-ephem-wheel-cache-1ikebtcr/wheels/77/6e/4a/3529e563189e81cf9b666571c9ce05e32b21b691f215f36d6b Successfully built waveshare-epd Installing collected packages: waveshare-epd Attempting uninstall: waveshare-epd Found existing installation: waveshare-epd 0.0.0 Uninstalling waveshare-epd-0.0.0: Successfully uninstalled waveshare-epd-0.0.0 Successfully installed waveshare-epd-0.0.0

I don't see anything weird in there.
