### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by leonarrxd** [dr-mod/zero-btc-screen#33]
If i try to do my first start up with the code: python3 ~/zero-btc-screen/main.py 
It has an Error.
Fileno
<img width="814" alt="Screenshot 2022-12-23 at 14 22 26" src="https://user-images.githubusercontent.com/121298714/209343117-6f81acfc-c06c-4d77-8520-6325a1f56304.png">

**Comment by dr-mod** [comment]
Hey @leonarrxd, based on the stack trace, I'd say it's most likely that you didn't enable SPI in raspi-config.

**Comment by leonarrxd** [comment]
Altough it was already on, and i just tried stuff and now it works, thank you! 
And i really like this BTC Display
