### ISSUE TITLE
Program just doesn't start

### ISSUE THREAD

**Issue by st3v3n041** [dr-mod/zero-btc-screen#39]
Everything actually works for me but in the end the program just doesn't start. I do troubleshoot I get the following:

st3v3n@raspberrypi:~ $  sudo journalctl -f -u btc-screen.service
-- Journal begins at Tue 2023-12-05 04:07:44 CET. --
Jan 24 14:03:11 raspberrypi systemd[1]: Started zero-btc-screen.
Jan 24 14:03:11 raspberrypi systemd[404]: btc-screen.service: Changing to the requested working directory failed: No such file or directory
Jan 24 14:03:12 raspberrypi systemd[404]: btc-screen.service: Failed at step CHDIR spawning /usr/bin/python3: No such file or directory
Jan 24 14:03:12 raspberrypi systemd[1]: btc-screen.service: Main process exited, code=exited, status=200/CHDIR
Jan 24 14:03:12 raspberrypi systemd[1]: btc-screen.service: Failed with result 'exit-code'.
Jan 24 14:03:12 raspberrypi systemd[1]: btc-screen.service: Scheduled restart job, restart counter is at 5.
Jan 24 14:03:12 raspberrypi systemd[1]: Stopped zero-btc-screen.
Jan 24 14:03:12 raspberrypi systemd[1]: btc-screen.service: Start request repeated too quickly.
Jan 24 14:03:12 raspberrypi systemd[1]: btc-screen.service: Failed with result 'exit-code'.
Jan 24 14:03:12 raspberrypi systemd[1]: Failed to start zero-btc-screen.

Can anyone help...plz? :-)

**Comment by dr-mod** [comment]
Double check if your copy zero-btc-screen is available at `/home/pi/zero-btc-screen`. It's likely that the issue above is caused by a missing _WorkingDirectory_.

**Comment by st3v3n041** [comment]
Thanks....but it's there:


st3v3n@raspberrypi:~ $ ls /home/st3v3n/zero-btc-screen
config             data  LICENSE  main.py       __pycache__
configuration.cfg  docs  logs.py  presentation  README.md

**Comment by dr-mod** [comment]
The problem you're having is due the name of the user, by default it's `pi` and you have `st3v3n`. You can either move the _zero-btc-screen_ to `/home/pi/` or change the config files to make use of the `st3v3n` path.

**Comment by st3v3n041** [comment]
YES!!! That was the mistake: I changed the config file also and now it works! Definitely my fault! Enjoy your coffee ;-)

**Comment by st3v3n041** [comment]
Donated everyone this HERO a coffee!!!
