### ISSUE TITLE
Exception: Could not determine Jetson model

### ISSUE THREAD

**Issue by rgegergergregrger** [dr-mod/zero-btc-screen#9]
I have the examples from waveshare up and running.

Trying to run your code: "python3 ~/zero-btc-screen/main.py"
I get the following message: "Exception: Could not determine Jetson model"
![IMG_0534](https://user-images.githubusercontent.com/85041362/120087018-acda5b80-c0e4-11eb-8203-a70ab927c6a3.jpg)

Am I supposed to configure the model I'm using somewhere? I'm using a 2in13V2
Can anyone help me out here? Thank you!

**Comment by dr-mod** [comment]
Hey @rgegergergregrger, I think I've come across the same issue on one of my RPIs once working on another project with this screen, as far as I remember I had my RPi.GPIO library not working correctly, try to reinstall it.

**Comment by rgegergergregrger** [comment]
Thank you! This fixed the issue.
I wasn't able to reinstall manually through apt or pi. I used the pip ignore-installed option instead: `pip3 install --ignore-installed`

**Comment by dr-mod** [comment]
You're welcome! Glad it helped.
